#!/bin/sh
choice=$(printf "202\\n204\\n210\\n211\\n212\\nHCI\\nSD\\nGP\\nOS\\nAP" | dmenu -i -p "Module?")
[ ! -z $choice ] && notify-send "opening $choice"
case "$choice" in
    202|HCI) firefox --new-window "$LHCI"  > /dev/null ;;
    204|SD)  firefox --new-window "$LSOFT"  > /dev/null ;;
    210|GP)  firefox --new-window "$LGROUP"  > /dev/null ;;
    211|OS)  firefox --new-window "$LOS"  > /dev/null ;;
    212|AP)  firefox --new-window "$LADV"  > /dev/null ;;
esac
